/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlwaysOnRouteImport } from './routes/always-on'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BacktestRouteImport } from './routes/backtest'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as UniverseRouteImport } from './routes/universe'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as ApiTickRouteImport } from './routes/api/tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlwaysOnRoute = AlwaysOnRouteImport.update({
  id: '/always-on',
  path: '/always-on',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BacktestRoute = BacktestRouteImport.update({
  id: '/backtest',
  path: '/backtest',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseRoute = UniverseRouteImport.update({
  id: '/universe',
  path: '/universe',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTickRoute = ApiTickRouteImport.update({
  id: '/api/tick',
  path: '/api/tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/always-on': typeof AlwaysOnRoute
  '/audit': typeof AuditRoute
  '/backtest': typeof BacktestRoute
  '/journal': typeof JournalRoute
  '/signals': typeof SignalsRoute
  '/universe': typeof UniverseRoute
  '/venues': typeof VenuesRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/always-on': typeof AlwaysOnRoute
  '/audit': typeof AuditRoute
  '/backtest': typeof BacktestRoute
  '/journal': typeof JournalRoute
  '/signals': typeof SignalsRoute
  '/universe': typeof UniverseRoute
  '/venues': typeof VenuesRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/always-on': typeof AlwaysOnRoute
  '/audit': typeof AuditRoute
  '/backtest': typeof BacktestRoute
  '/journal': typeof JournalRoute
  '/signals': typeof SignalsRoute
  '/universe': typeof UniverseRoute
  '/venues': typeof VenuesRoute
  '/api/tick': typeof ApiTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/always-on'
    | '/audit'
    | '/backtest'
    | '/journal'
    | '/signals'
    | '/universe'
    | '/venues'
    | '/api/tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/always-on'
    | '/audit'
    | '/backtest'
    | '/journal'
    | '/signals'
    | '/universe'
    | '/venues'
    | '/api/tick'
  id:
    | '__root__'
    | '/'
    | '/always-on'
    | '/audit'
    | '/backtest'
    | '/journal'
    | '/signals'
    | '/universe'
    | '/venues'
    | '/api/tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlwaysOnRoute: typeof AlwaysOnRoute
  AuditRoute: typeof AuditRoute
  BacktestRoute: typeof BacktestRoute
  JournalRoute: typeof JournalRoute
  SignalsRoute: typeof SignalsRoute
  UniverseRoute: typeof UniverseRoute
  VenuesRoute: typeof VenuesRoute
  ApiTickRoute: typeof ApiTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/always-on': {
      id: '/always-on'
      path: '/always-on'
      fullPath: '/always-on'
      preLoaderRoute: typeof AlwaysOnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backtest': {
      id: '/backtest'
      path: '/backtest'
      fullPath: '/backtest'
      preLoaderRoute: typeof BacktestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe': {
      id: '/universe'
      path: '/universe'
      fullPath: '/universe'
      preLoaderRoute: typeof UniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tick': {
      id: '/api/tick'
      path: '/api/tick'
      fullPath: '/api/tick'
      preLoaderRoute: typeof ApiTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlwaysOnRoute: AlwaysOnRoute,
  AuditRoute: AuditRoute,
  BacktestRoute: BacktestRoute,
  JournalRoute: JournalRoute,
  SignalsRoute: SignalsRoute,
  UniverseRoute: UniverseRoute,
  VenuesRoute: VenuesRoute,
  ApiTickRoute: ApiTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
